const username = [
    "StarGazer123",
    "PixelWarrior",
    "MysterySeeker",
    "MoonlightDancer",
    "TechGeek42",
    "NinjaPanda88",
    "CaptainAdventure",
    "CoffeeLover21",
    "WizardInSneakers",
    "SunnySmiles77",
    "SongbirdSerenade",
    "CyberPirateX",
    "AquaExplorer99",
    "ChocoChipNinja",
    "GalacticTraveler",
    "ScribbleWizard",
    "RainbowChaser66",
    "GamerJester",
    "BookwormNinja",
    "PineapplePizzaFan",
];

const email = [
    "example1@example.com",
    "example2@example.com",
    "example3@example.com",
    "example4@example.com",
    "example5@example.com",
    "example6@example.com",
    "example7@example.com",
    "example8@example.com",
    "example9@example.com",
    "example10@example.com",
    "example11@example.com",
    "example12@example.com",
    "example13@example.com",
    "example14@example.com",
    "example15@example.com",
    "example16@example.com",
    "example17@example.com",
    "example18@example.com",
    "example19@example.com",
    "example20@example.com",
];

const thoughts = [
"Life is a journey, not a destination.",
"Sometimes, the best way to find yourself is to lose yourself in nature.",
"In the chaos of life, find moments of stillness to hear your own thoughts.",
"The best memories are often made when you least expect them.",
"Failure is not the end; it's a stepping stone to success.",
"The universe is vast, and our existence is but a blink in its timeline.",
"A cup of tea can solve many of life's problems.",
"Kindness costs nothing but can mean everything to someone in need.",
"Music is the soundtrack to our lives, with each song carrying a unique story.",
"Dreams are the whispers of the soul, urging us to pursue our desires.",
"Numbers and equations hold the secrets of the universe.",
"Silence is golden; it allows us to listen to our inner wisdom.",
"Books are windows to other worlds, offering adventures without leaving your chair.",
"Laughter is contagious; it spreads joy like wildfire.",
"Stars are distant reminders of the vastness of the cosmos.",
"The smell of freshly baked cookies can transport you back to childhood.",
"Time never stops; it marches on, shaping our lives with each passing moment.",
"A smile is a universal language that transcends barriers.",
"Rainbows are nature's way of painting the sky with hope.",
"Love is the most powerful force in the universe, capable of incredible feats.",
];

const reactions = [
"Wow, that's amazing!",
"I can't believe it!",
"This is truly incredible.",
"I'm speechless.",
"My mind is blown!",
"That's mind-boggling!",
"I'm so impressed!",
"I'm in awe of this.",
"This is beyond words.",
"I'm completely taken aback.",
"I'm over the moon!",
"I'm thrilled by this.",
"I'm genuinely surprised.",
"This is a game-changer.",
"I'm so happy right now.",
"I can't stop smiling.",
"I'm filled with joy.",
"I'm on cloud nine!",
"This warms my heart.",
"I'm positively elated!",
]

